# expert user interface
# ./mvnw clean spring-boot:run
# ./mvnw clean install
# java -jar target/Procurement*
#****************************************************
#              DELETE THESE FILES FOR KAFKA
#****************************************************
C:\Users\<username>\AppData\Local\Temp
C:\tmp

#****************************************************
#         COMMANDS TO RUN KAFKA ON WINDOWS
#****************************************************
D:\kafka_2.13-3.3.1\bin\windows\zookeeper-server-start.bat D:\kafka_2.13-3.3.1\config\zookeeper.properties
D:\kafka_2.13-3.3.1\bin\windows\kafka-server-start.bat D:\kafka_2.13-3.3.1\config\server.properties
D:\kafka_2.13-3.3.1\bin\windows\kafka-topics.bat --bootstrap-server=localhost:9092 --list
D:\kafka_2.13-3.3.1\bin\windows\kafka-console-consumer.bat --bootstrap-server localhost:9092 --topic backlog-topic --from-beginning
###
#****************************************************
#              GET GROSS SALES REVENUE
#****************************************************
# curl -v http://localhost:8790/bi-sales/gross-profit | json_pp
GET http://localhost:8790/bi-sales/gross-profit

###
#****************************************************
#         GET INDIVIDUAL PRODUCT REVENUE
#****************************************************
# encode supplier name first.
# https://www.url-encode-decode.com/
# curl -v http://localhost:8790/bi-sales/product/?productName=GhostWhite+quam | json_pp
GET http://localhost:8790/bi-sales/product/?productName=AntiqueWhite+incidunt HTTP/1.1

