@hostname = localhost
@port = 8788
@host = {{hostname}}:{{port}}
@api = productInventory
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@ID = 2


# expert user interface
# ./mvnw clean spring-boot:run
# ./mvnw clean install
# java -jar target/Procurement*


###
curl -X POST http://{{host}}/{{api}} \
 -H 'Content-type:application/json' \
 -d '{
        "name": "crank",
        "price": 122.3,
        "description": "sample description",
        "quantity": 12
    }'

###

curl -X PUT http://{{host}}/{{api}}/777678 \
 -H 'Content-type:application/json' \
 -d '{
        "name": "dssfgdsfg",
        "price": 33.3,
        "description": "sample description",
        "quantity": 11
    }'

###
curl -X PUT http://{{host}}/{{api}}/777677/part \
 -H 'Content-type:application/json' \
 -d '{
    "partName": "Crank",
    "partDescription": "metal oxide",
    "manufacturer": "Fuller, Allen and Smith",
    "quantity": 30
    }'

###
curl -X PUT http://{{host}}/{{api}}/777677/part/30423 \
 -H 'Content-type:application/json' \
 -d '{
    "partName": "dank",
    "partDescription": "shafted",
    "manufacturer": "Long, Ellis and Lara"
}'

###
GET http://{{host}}/{{api}}/parts HTTP/1.1
###

curl -X POST http://{{host}}/{{api}}/check \
 -H 'Content-type:application/json' \
 -d '{
        "name": "crank",
        "price": 122.3,
        "description": "sample description",
        "quantity": 12
    }'

###

GET http://{{host}}/{{api}}/parts/30423 HTTP/1.1
###

# curl -v localhost:8080/suppliers | json_pp
GET http://{{host}}/{{api}} HTTP/1.1

###


# curl -v localhost:8080/suppliers/1
GET http://{{host}}/{{api}}/777677 HTTP/1.1

###