server.port: 8790
spring.cloud.stream.bindings:
  process-in-0:
        destination: backlog-topic
  process-in-1:
        destination: backorder-topic        
  process-out-0:
        destination: bi-topic
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9092
  configuration:
    commit.interval.ms: 1000
  serdeError: logAndContinue
spring.cloud.stream.kafka.streams.bindings:
  processBacklog-in-0:
    consumer:
      configuration:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: mercury.shareDomain.events.Backlog
  # process-in-1:
  #   consumer:
  #     configuration:
  #       default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  #       default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
  #       spring.json.trusted.packages: '*'
  #       spring.json.value.default.type: mercury.shareDomain.events.Backorder
      #materializedAs: incoming-store-1
  processBacklog-out-0:
    producer:
      configuration:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: mercury.business.model.SalesIntel

  processBackorder-in-0:
    consumer:
      configuration:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: mercury.shareDomain.events.Backorder
  processBackorder-out-0:
    producer:
      configuration:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: mercury.business.model.SalesIntel
        
#spring.cloud.stream.kafka.streams.binder.stateStoreRetry.maxAttempts: 3



