import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function procurement() {
  const [keyword, setKeyword] = useState("suppliers");
  const [data, setData] = useState([]);
  const fetchData = () => {
    fetch(`http://localhost:8080/${keyword}`)
      .then((response) => response.json())
      .then((data) => setData(data._embedded.supplierList))
      .catch((err) => console.error(err));

  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="http://localhost:8080/suppliers">Suppliers</a>
        </h1>

        <div className={styles.grid}>
          {data.map((supplier, index) => (
            <a key={index} href={supplier['_links']['self']['href']} className={styles.card}>
              <h2>{supplier['companyName']} &rarr;</h2>
              <p>Based in {supplier["base"]} with {supplier['contacts'].length} contacts.</p>
              {supplier['contacts'].map((c, i) => (
                <div className={styles.grid}>
                <a href={`http://localhost:8080/contacts/${c['id']}`} className={styles.card}>
                  <p>id: {c['id']}</p>
                  <p>{c['position']} &rarr;</p>
                </a>

                </div>
              ))}
              
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/bicycle_with_basket.png"
              alt="Mercury Logo"
              width={72}
              height={29}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
