@hostname = localhost
@port = 8789
@host = {{hostname}}:{{port}}
@api = sales
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@ID = 2


# expert user interface
# ./mvnw clean spring-boot:run
# ./mvnw clean install
# java -jar target/Procurement*


###
curl -X POST http://{{host}}/{{api}}/online \
 -H 'Content-type:application/json' \
 -d '{"productName": "crank", "quantity": 12, "dateTime": 1662363000}'

###


curl -X POST http://{{host}}/{{api}}/store \
 -H 'Content-type:application/json' \
 -d '{"address": "fake address", "managerName": "steve"}'

###

# curl -v localhost:8789/sale | json_pp
GET http://{{host}}/{{api}} HTTP/1.1

###

# curl -v localhost:8789/sale/9999900 | json_pp
GET http://{{host}}/{{api}}/9999900 HTTP/1.1

###

# curl -v localhost:8789/sale/store | json_pp
GET http://{{host}}/{{api}}/store HTTP/1.1

###


# curl -v localhost:8789/sale/store/33333200 | json_pp
GET http://{{host}}/{{api}}/store/33333200 HTTP/1.1

###

curl -X POST http://{{host}}/{{api}}/store/33333200 \
 -H 'Content-type:application/json' \
 -d '{"productName": "crank", "quantity": 12, "dateTime": 1662363000}'

###


curl -X PUT http://{{host}}/{{api}}/777677/part \
 -H 'Content-type:application/json' \
 -d '{
    "partName": "Crank",
    "partDescription": "metal oxide"
}'

###

curl -X POST http://localhost:8080/suppliers \
 -H 'Content-type:application/json' \
 -d '{"companyName": "Soft Tails", "base": "Campbelltown"}'

###


# curl -v localhost:8080/suppliers | json_pp
GET http://{{host}}/{{api}} HTTP/1.1

###

# curl -v localhost:8080/suppliers/1
GET http://{{host}}/{{api}}/2 HTTP/1.1

###
###

curl -X PUT http://localhost:8080/suppliers/2 \
-H 'Content-type:application/json' \
-d '{"companyName": "Round Tires", "base": "Brisbane"}'

###

PUT http://{{host}}/suppliers/{{ID}} HTTP/1.1
Content-Type: {{contentType}}

{
    "companyName": "Round Tires",
    "base":"Brisbane"
}

###

# curl -v localhost:8080/suppliers/1
GET http://{{host}}/suppliers/1 HTTP/1.1

###

curl -X DELETE localhost:8080/suppliers/1

###
DELETE  http://{{host}}/{{api}}/1 HTTP/1.1

###

# curl -i -X PUT http://localhost:8080/suppliers/1/contact/4
PUT http://{{host}}/{{api}}/1/contact/4 HTTP/1.1

###

# curl -i -X PUT http://localhost:8080/suppliers/1/contact/5
PUT http://{{host}}/{{api}}/1/contact/5 HTTP/1.1

###

# curl -i -X PUT http://localhost:8080/suppliers/1/contact/6
PUT http://{{host}}/{{api}}/1/contact/6 HTTP/1.1

###
# curl -v localhost:8080/suppliers/1
GET http://{{host}}/suppliers/1 HTTP/1.1

###