@hostname = localhost
@port = 8789
@host = {{hostname}}:{{port}}
@api = sales
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@ID = 2


# expert user interface
# ./mvnw clean spring-boot:run
# ./mvnw clean install
# java -jar target/Procurement*

###
#****************************************************
#                   CREATE A STORE
#****************************************************
curl -X POST http://{{host}}/{{api}}/store \
 -H 'Content-type:application/json' \
 -d '{"address": "fake address", "managerName": "steve"}'

###
#****************************************************
#                CREATE A STORE SALE
#****************************************************
curl -X POST http://{{host}}/{{api}}/store/33333200 \
 -H 'Content-type:application/json' \
 -d '{"productName": "crank", "quantity": 1}'

###
#****************************************************
#                   GET ALL STORES
#****************************************************
GET http://{{host}}/{{api}}/store

###
#****************************************************
#                   GET ONE STORE
#****************************************************
GET http://{{host}}/{{api}}/store/33333200

###
#****************************************************
#               GET ONE STORES SALES
#****************************************************
GET http://{{host}}/{{api}}/store/33333200/purchases

###
#****************************************************
#                 CREATE ONLINE SALE
#****************************************************
curl -X POST http://{{host}}/{{api}}/online \
 -H 'Content-type:application/json' \
 -d '{"customerName": "Bill Murray", "address": "13 The Farm, Adelaide, 4321", "productName": "crank", "productId":777677, "quantity": "2"}'

###
#****************************************************
#                GET ALL ONLINE SALES
#****************************************************
GET http://{{host}}/{{api}}/online HTTP/1.1

###
#****************************************************
#                GET ONE ONLINE SALE
#****************************************************
GET http://{{host}}/{{api}}/online/9999901 HTTP/1.1